server:
  port: 8080

spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    topics:
      - name: payment-command
        partitions: 1
        replication-factor: 1
      - name: payment-command-result
        partitions: 1
        replication-factor: 1

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
